### ISSUE TITLE
The quantity of days changes wrong [Workflow reminders]

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#1010]
**Steps to reproduce:**

1. Open the "Workflow reminds" sub card in the settings 
2. Try to change the quality of the days 

**Expected result:**

User change the  quantity of days in the right way
 
**Actual result:**

The quantity of days of the nonconformity/risk and improvement plans changes wrong (incorrect), please see below

https://drive.google.com/file/d/1wTATuRnndjrRNiaz1iuwhQStUF--CeSz/view?usp=sharing

**Comment by Dartv** [comment]
This is so frustrating to deal with because blaze doesn't have any lifecycle methods.
This happens because when you update a value of one field, it takes time to reach the server and send back the response. Because of that, when you try to change the other value immediately, the response from previously changed value comes back and updates the component to its original value.
A value is 0
B value is 0
Change A value to 1
Immediately start changing B value to 1, 2, etc...
Field A loses focus and makes request to the server
Response comes back with A and B values from database
Field A and B receive these values
Field B did not lose focus and did not make a request with the new value
Field B goes back to original value

That's why meteor pub/sub and blaze is so hard to deal with...

**Comment by Dartv** [comment]
All those old org settings subcards are 2+ years old legacy code and should be rewritten with react + apollo anyway. @Praxie maybe we shouldn't waste time on this?

**Comment by Dartv** [comment]
@Praxie There's also no reason to make request on every focus out. Would be better if we had a submit button at the bottom of each subcard

**Comment by Dartv** [comment]
These are related https://github.com/Pliohub/Plio/issues/1002 https://github.com/Pliohub/Plio/issues/1001

**Comment by Praxie** [comment]
@Dartv Meteor has a latency compensation. Why the field isn't updated immediately?

**Comment by Dartv** [comment]
@Praxie meteor methods are asynchronous, so there will be a short delay anyway.
The decision to use subscriptions with field updates on blur is ultimately wrong and is only caused pain

**Comment by Dartv** [comment]
The only solution to this I can think of is implementing a save button that will submit the whole form

**Comment by Dartv** [comment]
Another one is to rewrite this whole subcard with react and check in `shouldComponentUpdate` if the field is focused. If it is, then do not update the component.
