### ISSUE TITLE
 The "Lessons Learned"  must not display as a button [Nonconformity,PG and Risk] 

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#1039]
**Steps to reproduce:**

1. Open the nonconformity(risk or PG)
2. Enter some lessons and come back to page of the nonconformity (risk or PG)

**Expected result:**

Lessons displayed as a text 

**Actual result:**

The "Lessons Learned" are displayed as a buttons

![image](https://user-images.githubusercontent.com/34645257/39817670-7405379c-53a7-11e8-941d-9a05b8d59491.png)

**Comment by Dartv** [comment]
@sives is this necessary?

**Comment by sives** [comment]
@Dartv there are two possible valid user interface treatments for this:

1. Display the text of the Lesson Learned title (easier solution)
or
2. Display as a button, but the button has to work (harder solution, but better)
Clicking on the button should open a read-only modal displaying the Lesson Learned details.

What is not acceptable is to display a button but for nothing to happen when you click it.  If solution 2 is fairly easy to implement, then let's do it. Otherwise implement solution 1.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1046

**Comment by Praxie** [comment]
![screen shot 2018-05-17 at 10 25 35 pm](https://user-images.githubusercontent.com/2095940/40199138-3cd410ec-5a21-11e8-97c2-128063d000e6.png)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/10/18 - 05/10/18
Work session total: 0:49:32

Grand total: 0:49:32
