### ISSUE TITLE
Can not change "Completed by" value in the CA after completion [Nonconformity]

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#1043]
**Steps to reproduce:**

1. Open the nonconformity
2. Create the CA 
3. Select another one "To be completed by" and complete CA 

"Expected result:" 

The selected "To be completed by" value have to be saved in the field and notification message sent

**Actual result:**

A selected "To be completed by" value didn't save after completion, video below 

https://drive.google.com/file/d/1DdXJ0Uy8N_sog6qTNEOAQxc1tJpIU6GI/view?usp=sharing

**Comment by Dartv** [comment]
This is the correct behavior. After completion "Completed by" field is shown instead of "To be completed by". It makes sense that it shows the current user because you are the one who completed the action. You have a "Can complete any action" superpower so you can complete any action even if "To be completed by" is not the current user.

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/10/18 - 05/10/18
Work session total: 0:42:17

Grand total: 0:42:17
