### ISSUE TITLE
Traffic light symbols missing in Work inbox

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1083]
Most of the round traffic light symbols are missing in the LHS list view in the Work inbox (all of the list views in the Work inbox seem to suffer from this problem).  Since every item in the list view has a defined status, I expect to see a traffic light corresponding in colour to this status.

![screen shot 2018-05-16 at 16 29 37](https://user-images.githubusercontent.com/2330529/40127386-2a28f278-5927-11e8-90c0-973621c33713.png)

**Comment by Dartv** [comment]
That's because almost all of your items are in progress. This is not a bug, I don't think so. It has always been like that. Currently, the traffic light symbol is decided based on **work item** status associated with that item (nc, action, etc.). I think at some point we decided to hide the default grey `in progress` status.
These are the traffic lights:
- In progress - hidden
- Due today - yellow
- Overdue - red
- Completed - green

**Comment by sives** [comment]
OK, yes, you are correct.  Sorry, I should have remembered this!

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/18/18 - 05/18/18
Work session total: 0:37:01

Grand total: 0:37:01
