### ISSUE TITLE
Expand functionality (More/Less) for new modals

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1285]
**More/less button behaviour**
The more/less button is only visible when no new subcards have been added.  The  button is not displayed when at least one new subcard has been added - the user sees the fully-expanded version of the card, containing at least the four primary sub cards (Customer insights or Value components, Actively  manage, Files and Notify changes).  If the user has removed all new data and new subcards, then the more/less button is displayed again.

**Comment by Praxie** [comment]
Hi @sives, I'm wondering if we still can simplify this feature. It doesn't seem to be very straightforward to the end user. 

What if clicking on the More/Less button will set the global config that will work for all sections on the Canvas view? If you expanded 1 card, all other cards on the canvas screen will be displayed expanded, unless you click on the More/Less button again (in any card on the canvas screen).

**Comment by sives** [comment]
@Praxie The key reason for this feature is to reduce the visual complexity of the cards when users are starting out with Plio canvas editor and don't yet understand all the features in the system.  Canvas design is a 3 stage process.  In stage 1, the user is just creating a lot cards across the canvas boxes with the minimum amount of data.  In stage 2, the user goes to the next level of detail in defining the customer insights and value components.  In stage 3, the user decides to implement the new business model and starts adding operational information e.g. standards, risks etc.  I'm trying to keep the card design as simple as possible at the outset, so as not to discourage stage 1 users with the full complexity of the system.  

Changing More/Less to be a global config might be confusing, because all other global config parameters are set in Org settings or User preferences.  Personally, I think it is more intuitive if the More/Less button works on just one card at a time.  

However, I do think it would be a smart idea to move the Customer insights subcard to the top section of the Customer segment card, and the Value components subcard to the top section of the Value proposition card.  Then the user wouldn't have to click on 'More' to reveal this important functionality.

**Comment by Dartv** [comment]
This will add more complexity. If we'd show more/less button all the time, we could fetch all the data for the top section right away and then all the data for subcards when the user clicks on more/less button. Less data to load = less traffic spent. But your requirements leave us with only one choice of loading all the data right away, even if the user doesn't need it.

**Comment by sives** [comment]
OK, then perhaps we should stick with the original design as in the prototype

**Comment by Dartv** [comment]
It's a problem in 3rd world countries. But if you don't expect customers from there it's ok.

**Comment by sives** [comment]
My target customers are all in US and EU, so don't need to worry so much about low bandwidth connections

**Comment by Praxie** [comment]
Actually, I think that having the global config is a good thing, the user won't even think about this. 
And this makes sense for Stage 2 in the user journey. Once the user open a more detailed view on some card, it'll remain open for others. That's the point of the second stage. The system will expect the user to add more details to all cards on the Canvas screen as soon as he'll decide to start this process.

**Comment by Praxie** [comment]
@sives what's your opinion about this?

**Comment by sives** [comment]
@Praxie I'd prefer to deal with Stage 2 by placing the Customer insights and Value components subcards within the top section of the Customer segments and Value components cards

**Comment by sives** [comment]
@Praxie I'd be comfortable with implementing the More button as a global config feature subject to the following:
1. We move the Customer insights and Value components subcards to the top section of the Customer segments and Value components cards 
2. We load all the data in the card at the beginning, so there is no latency when the user clicks on the More button

**Comment by Dartv** [comment]
@Praxie adding global config wont make things easier, but the other way around. Why are you so desperate to push that idea?

**Comment by Dartv** [comment]
Should be no problem if we'll load all the data at the beginning. It's just a matter of checking if data exists.

**Comment by Praxie** [comment]
@sives does it look OK for you? It doesn't feel right for me for some reason.
![screen shot 2018-08-16 at 3 47 01 pm](https://user-images.githubusercontent.com/2095940/44209288-afee4200-a16b-11e8-89ca-cb6cbb6eec46.png)
![screen shot 2018-08-16 at 3 47 10 pm](https://user-images.githubusercontent.com/2095940/44209289-afee4200-a16b-11e8-9070-cb838d441fd2.png)

**Comment by sives** [comment]
You're right - it doesn't look quite right, lets keep this subcard in the lower section

**Comment by sives** [comment]
Saving the state of the More/Less button for each canvas item is fine

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/1576
