### ISSUE TITLE
Re-assign document after the user gets deleted.

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1362]
Documents, that are linked to the user (by fields like Originator, Owner, To be completed by etc.) should be re-assigned to another user if the first one gets deleted.
We need to think of the best solution.

1. Link all documents to the org owner automatically.
2. Present the user with a dropdown input to select the new accountable user.

@sives @Dartv

**Comment by sives** [comment]
I would prefer option 2, since it reduces the number of operations required by the user. If someone leaves the organisation and is replaced by a new person who takes on the same role, the documents owned by the leaving person only need to be reassigned once, to the new person, and not twice (assigned to the Org owner, then assigned to the new incoming employee).

**Comment by Dartv** [comment]
@sives is this ok?
![](https://i.gyazo.com/b341e1cb9b812446c1af56c5ab89903f.png)

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1569
https://github.com/Pliohub/Plio/pull/1573
https://github.com/Pliohub/Plio/pull/1575

**Comment by sives** [comment]
Looks good.  I would re-word the text prompt slightly, to "Select user to take on your owner responsibilities"

**Comment by Dartv** [comment]
@sives "Select user to take on your owner responsibilities" is misleading since any user with the appropriate role can delete users. I changed it to "Select user to take on {user full name} owner responsibilities"

**Comment by sives** [comment]
@Dartv Yes, that's even better
