### ISSUE TITLE
User menu breaks on mobile

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1411]
![](https://i.gyazo.com/c17b60f37d39a66b77d6a72a6f1deddd.png)
On the dashboard screen the user menu slides off.
On the canvas screen it disappears

**Comment by Dartv** [comment]
@Praxie @sives maybe hide "Business operations view" part on mobile or render on a second row?

**Comment by sives** [comment]
@Dartv @Praxie it looks OK to me.  Jack has made a few small changes in latest version in the last couple of hours, perhaps you viewed it in the middle of his changes?   http://ui2.isometrica.io/ui1-3/index.html

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1415

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/46099013-5fd4b780-c1ce-11e8-9e98-5646046d8119.png)

**Comment by Praxie** [comment]
@Dartv I've moved this issue to Milestone 5a-3 & in progress, because it's not fixed in the Business operations view. And I'm not sure whether hiding the user information in the header is a good idea.

@sives 
1. "Business operations view" is too long to display it on mobile header. We should hide these strings and display only the org name. 
![screen shot 2018-09-26 at 9 11 33 pm](https://user-images.githubusercontent.com/2095940/46100058-31a4a700-c1d1-11e8-980d-7b58ea1b6d05.png)

2. It also makes sense to hide the  full name and display only the presence indicator with the arrow. What do you think?

**Comment by Dartv** [comment]
@Praxie you can clearly see that the PR I linked is not merged which means it's not in staging

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 09/26/18 - 09/26/18
Work session total: 0:39:31

Grand total: 0:39:31

**Comment by sives** [comment]
@Praxie 
1. I agree that the text string should be hidden and only display the org name on mobile, but it must be possible to see the words "Operations view" when you tap on the LHS down symbol.
2. I agree that it makes sense to hide the user name and only display the presence indicator on mobile, but it must be possible to see the user name when you tap on the RHS down symbol.

**Comment by sives** [comment]
@praxie I'm testing on 0.3.55 and it's displaying a combined truncated title "Ka..Operations view" on the header bar.  It should display just the org name, truncated if necessary.

**Comment by sives** [comment]
Looks fine on 0.3.56
