### ISSUE TITLE
Notifications for canvas subcards

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1516]
We need to notify the user if any item is added/removed in any subcard (standards, goals, nonconformities, etc.)

**Comment by Dartv** [comment]
@sives Should every user listed in notify subcard be notified about creation/removal of a subcard item (standard, goal, etc.). In our current system notifications from fields like standards or departments are sent only to the document owner.

**Comment by sives** [comment]
In the current system, it makes sense to restrict the default notifications to the document owner and allow users to add to this list via the Notify subcard.  However, with the Canvas items, any user that adds a Canvas item will be interested to hear about addition or removal of other Canvas items by any other user (this is not so true about Standards, NCs and Risks).  

Its quite complicated to track just those users that have added Canvas items and put these automatically into the Notify users list for any other Canvas items.  So I tried to make a simpler solution, which was to allow the Org owner to add users to the default list via a new option in Org settings (see also #1511 ).  However, if it turns out to be simpler to do this via the automatic method, this would be the best way.

**Comment by Dartv** [comment]
I'm not asking about canvas items, but canvas item's subcards (standards, goals, lessons, etc.). Should all of the users in the notify subcard of canvas item be notified about any changes to its other subcards or only the document owner?

**Comment by sives** [comment]
Now I get what you're asking.  The answer to your question is "all the users in the Notify subcard of the canvas item should be notified about any changes to its other sub cards".
