### ISSUE TITLE
Audit configs for customer element relations

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#1609]
We have notifications for customer elements match but not audit.

**Comment by Dartv** [comment]
@sives should we create audit logs for both documents when matching customer elements?
![](https://i.gyazo.com/f5065b126d1acfd0e2f513d41392b641.png)
In the screenshot above there is one log for each document.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1613

**Comment by sives** [comment]
@Dartv  The audit log should be displayed at the bottom of each canvas card (after clicking the More button).  There is only one log per card, just like other Plio logs e.g. at the bottom of the Standards card or the Nonconformity card.   Within each audit log, events are displayed in chronological order.  So I would not create 2 separate lists, one for NE1 and one for NE2.  Instead, I would just display each log event in isolation, in one list, in chronological order.  Does this answer your question?

**Comment by Praxie** [comment]
Hi @sives, we decided to not implement the Audit Log section for canvas items as you can remember.

**Comment by Dartv** [comment]
Daily recap is based on audit logs, so we can always add UI later

**Comment by sives** [comment]
@Dartv Sorry, yes you are correct, I mis-remembered the requirements.  Now I understand exactly the question you are posing.  

We should not create audit logs for both documents when creating daily recaps, because this just duplicates the same information.  Just create an audit record for one side of the link relationship.

(Please note that Needs can be linked to either Features or Benefits, and likewise Wants can be linked to either Features or Benefits)

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 11/30/18 - 11/30/18
Work session total: 1:07:47

Grand total: 1:07:47
