### ISSUE TITLE
Adding milestone to key goal from board

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1678]
Chrome web

Preconditions: created key goal

1. Open business operations view
2. Try add milestone to key goal

Bug: error displays. watch screenshot and video https://drive.google.com/open?id=17zQ8Q5QO0W34kqyHLEoyt7yRcoFtiCUa

![image](https://user-images.githubusercontent.com/41466462/50208483-f4882500-0379-11e9-8c34-fa255d342124.png)

**Comment by Dartv** [comment]
Fix is already merged

**Comment by sives** [comment]
@Praxie When creating a new milestone, there should be a default date rather than just a blank field (default should be 1 week after current date).  Also, the date field is incorrectly labelled as "Completion - target date" (which is the label used in the General Action field).  It should be labelled as "Date".

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/52445726-91726d80-2b34-11e9-95d6-6f26d0a71a22.png)
https://github.com/Pliohub/Plio/issues/1846
