### ISSUE TITLE
UI bug with integer input fields

### ISSUE THREAD

**Issue by vitalii7777** [Pliohub/Plio#1837]
Looks like this bug is present on integer input fields (in different sections). Just click on the field and will see.
Look on the picture:
![ui bug](https://user-images.githubusercontent.com/47181845/52051909-a3b14200-255d-11e9-8c54-0f4f1137cb3b.png)

**Comment by Dartv** [comment]
@sives can we make financial impact field as small as other number fields?
![](https://i.gyazo.com/c18e13da478152917ae0895675f37258.png)

**Comment by sives** [comment]
@Dartv   A user is likely to enter a much longer number string for financial impact compared to the issue number.  For example a financial impact could be as high as EUR 1000000.  This number would be too long to be visible in a field the same size as the Issue number field.  However, if the issue number field was made slightly bigger so that it could accommodate 7 digits without sideways scrolling, then I would be happy with this as a solution.

**Comment by Dartv** [comment]
Actually, we can leave them as they are. Removing this "x" button is easy.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/1868

**Comment by Praxie** [comment]
![image](https://user-images.githubusercontent.com/2095940/52500469-c17a4900-2be6-11e9-9506-ad7debe8b8b6.png)
![image](https://user-images.githubusercontent.com/2095940/52500484-cd660b00-2be6-11e9-9e09-5109aafe1331.png)

**Comment by sives** [comment]
@Praxie  Works fine now

**Comment by Dartv** [comment]
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 02/01/19 - 02/06/19
Work session total: 2:00:11

Grand total: 2:00:11
