### ISSUE TITLE
Improve email validation

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#301]
When a user is registering for the first time, or inviting a new user, it is easy to enter an incorrect email address.  For example a user on Plio today registered with the email address eidenttower@gmail.con.   It's really easy to enter .con instead of .com.  Let's check for this specific error (i.e. .con instead of .com) in our validation code.

**Comment by Praxie** [comment]
@sives It doesn't sound like a good approach. 
The list of possible email domains is huge.

**Comment by Praxie** [comment]
@sives Maybe it's better to provide a way to change the email address on the waiting page?
![screen shot 2016-11-03 at 12 12 41 pm](https://cloud.githubusercontent.com/assets/2095940/19962129/e9188fa8-a1be-11e6-824a-6bce87dafca6.png)

**Comment by Praxie** [comment]
![screen shot 2016-11-03 at 12 37 05 pm](https://cloud.githubusercontent.com/assets/2095940/19962850/415c4990-a1c2-11e6-9c66-e3fe566dea67.png)

(these are mockups)

**Comment by sives** [comment]
I agree that my original idea of checking against all the top level domains is not a good one.  But I think my second idea of just checking for the one specific misspelling (.con instead of .com) is OK.  I don't want to provide the user with an option to change their email address - it will confuse some users by providing them with this option at this stage.

**Comment by Praxie** [comment]
@sives I agree. I thought that you want to validate different possible domains.

**Comment by Praxie** [comment]
@RomanValihura /Plio/app/imports/startup/client/useraccounts.js
Find a way to add a custom email validation. Currently, we need to check for the one specific misspelling (.con instead of .com). 
https://github.com/meteor-useraccounts/core/blob/master/Guide.md
Form Fields Configuration:
re - RegExp - Possibly specifies the regular expression to be used for the field's content validation. Validation is performed both client-side (at every input change if continuousValidation option is set to true) and server-side on form submit.

**Comment by RomanValihura** [comment]
fixed https://github.com/Pliohub/Plio/pull/306

**Comment by Praxie** [comment]
**0.2.53**
