### ISSUE TITLE
Improvement plan notification

### ISSUE THREAD

**Issue by RevelsGit** [Pliohub/Plio#415]
This feature is already partially implemented (Github issue 60) and needs to be finished off.   Provision for customising the frequency Reminders for Improvement plans is made in the SC27 Workflow reminders subcard. (see Standard subcard spec v1.2).  We also need to make provision for the user to switch off this type of notification.

**Comment by Praxie** [comment]
@sives currently, the reminder notification looks this way:
![screen shot 2017-01-31 at 3 09 55 pm](https://cloud.githubusercontent.com/assets/2095940/22466093/5ba6f9da-e7c7-11e6-8039-be4bdc18369e.png)

The "click here" link removes the user from the Notify changes list. So I'm not sure if it's a good idea. In one hand, we can't have so much different notification types that can be switched off because it'll be very hard to manage them properly. In the other hand, it may be wrong to remove user from the Notify changes list because he will stop receiving notifications about document changes.

**Comment by sives** [comment]
I'm happy with it working this way.  If a user clicks on "Click here" then he is indicating that this specific document is not relevant to him, so he doesn't need to see either type of notification.
