### ISSUE TITLE
Data export bug in the staging application

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#426]
![9a90623fde1af8ffaedc5e4d3b683662](https://cloud.githubusercontent.com/assets/2095940/21820517/a26f183e-d778-11e6-83fc-7def43d5c8cc.gif)

**Comment by Praxie** [comment]
**Plio version 0.2.78**

**Comment by sives** [comment]
Two issues, one small and one bigger issue.

1.  Button label
Button under top right hand side 3-dots button should be labelled "Data export" and not "Export Data" to match the label of the Data export card.

2. Download file not created properly in Safari
When you select some fields and click on the "Download CSV file" button in Chrome, everything works as expected.  A CSV-formatted file is created and downloaded, with a link to the file appearing at the bottom left hand side of the browser user interface.  The user then double-clicks on this link to open the file in Excel.   In Safari, this does not happen.  Instead the CSV data is rendered on screen in the browser window.

![screen shot 2017-01-12 at 11 41 48](https://cloud.githubusercontent.com/assets/2330529/21888427/2766fdd8-d8bc-11e6-8296-60c567f16cce.png)

**Comment by RomanValihura** [comment]
@sives @Praxie Fixed in PR #430

**Comment by Praxie** [comment]
**Plio version 0.2.79**

**Comment by sives** [comment]
Working well.  In Risks screen, under Advanced filters, we need to include risks with the following status in the default download (i.e. checkbox should be blue) "Closed - actions completed" and "Closed - actions verified, standards reviewed".  This is because Risks are still current risks (even though their impact may be reduced) after actions relating to them have been closed

**Comment by RomanValihura** [comment]
fixed in PR #434

**Comment by sives** [comment]
Looking good
