### ISSUE TITLE
Incorrect notification message wording

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#450]
I spotted this notification message today in my email, which is confusingly worded.  I think it needs to be worded as follows, but I'm not 100% sure which type of notification event it refers to.  Let's discuss before fixing it.

 "The Preventative action PA7, which is completed, is waiting to be verified as effective by Michael Rokosh, with a target date of [date]."

**Comment by Praxie** [comment]
@sives could you provide an original message from that email?

**Comment by sives** [comment]
![confusing message](https://cloud.githubusercontent.com/assets/2330529/22433118/2d2c839e-e70f-11e6-9ad1-f896050735cd.png)

**Comment by sives** [comment]
I will also forward a copy to you by email

**Comment by Praxie** [comment]
@sives this is a "Notify changes" type of notifications.
As you see, we have the field with the same label in the UI.

![screen shot 2017-01-31 at 12 25 47 pm](https://cloud.githubusercontent.com/assets/2095940/22461057/6c4908da-e7b0-11e6-81df-5950297f7ced.png)

We can't customize a single message because it works for all fields in the document card, not only "to be verified by".

**Comment by Praxie** [comment]
So we can use any words in the notification, but only these 4 values are available in the current case (username, document type, document name, new value)

**Comment by sives** [comment]
Mike - based on your feedback I've amended this as follows:

"The Preventative action [PA7] [title], which is completed, is waiting to be verified as effective by Michael Rokosh, with a target date of [date]."

**Comment by Praxie** [comment]
**Plio version 0.2.86**

**Comment by markokruustuk** [comment]
Closed from GitHub
