### ISSUE TITLE
4. Create & edit Key goals superpower

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#735]

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/758

**Comment by Praxie** [comment]
@Dartv if the user has no superpower to add/edit key goals, we need to hide corresponding UI elements. ("+" button for now)
![screen shot 2018-03-07 at 7 33 15 pm](https://user-images.githubusercontent.com/2095940/37107956-68b816e2-223e-11e8-982f-4c513f3c6510.png)

![screen shot 2018-03-07 at 7 33 37 pm](https://user-images.githubusercontent.com/2095940/37107974-78eedf3c-223e-11e8-9281-12b2caa71519.png)

**Comment by Praxie** [comment]
Hi @sives, it turns out that we we can't show the Key Goal Edit modal to the user that has no Create & edit Key goals superpower. But in this way these users will have no access to Key Goals data because we have no read-only card. Should we create a read-only version for the Key Goal card? It will take 20-30 hours. Though usually, we display all read-only cards in the RHS main section (that's called a Card). Putting a Card into the modal window will cause the inconsistency.

**Comment by Praxie** [comment]
Other way would be to disable fields in the top section and prevent all subdocument subcards from opening (because it would be pretty hard to disables all fields in all subcards)

**Comment by sives** [comment]
Would it be possible to do the following simpler solution?
- Define the superpower as "Create & delete Key Goals" (any user can edit Key Goals and their subelements)
- Don't display the Add Key goal button if this superpower is disabled
- Don't display the Delete button at the bottom of the modal if this superpower is disabled

**Comment by sives** [comment]
A user that does not have the superpower "Create & delete Key goals" will not be able to see or edit the Risks sub card or the Lessons Learned sub card.

**Comment by Dartv** [comment]
https://github.com/Pliohub/Plio/pull/895
