### ISSUE TITLE
4. Limit displayed completed and deleted goals

### ISSUE THREAD

**Issue by Dartv** [Pliohub/Plio#768]
There should be an option in org settings to change the number of displayed "Completed & deleted goals". Default is 5.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/782

**Comment by Praxie** [comment]
@Serhiy91 
1. Key Goals subcard in Org settings should be under the Danger zone subcard.
2. Key Goals subcard in Org settings doesn't change anything because of exception:
![screen shot 2018-03-07 at 8 08 20 pm](https://user-images.githubusercontent.com/2095940/37109676-5218d96c-2243-11e8-8c3e-06d7e385af6b.png)

**Comment by Serhiy91** [comment]
@Praxie Key Goals subcard is **under** the Danger zone subcard.

**Comment by Serhiy91** [comment]
https://github.com/Pliohub/Plio/pull/809
